# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_mpsBART4_log_dmvn', PACKAGE = 'mpsBART4', x, Sigma)
}

sum_exclude_col <- function(mat, exclude_int) {
    .Call('_mpsBART4_sum_exclude_col', PACKAGE = 'mpsBART4', mat, exclude_int)
}

bspline <- function(x, x_obs) {
    .Call('_mpsBART4_bspline', PACKAGE = 'mpsBART4', x, x_obs)
}

sbart <- function(x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a) {
    .Call('_mpsBART4_sbart', PACKAGE = 'mpsBART4', x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a)
}

mat_init <- function(n) {
    .Call('_mpsBART4_mat_init', PACKAGE = 'mpsBART4', n)
}

vec_init <- function(n) {
    .Call('_mpsBART4_vec_init', PACKAGE = 'mpsBART4', n)
}

std_inv <- function(A, diag) {
    .Call('_mpsBART4_std_inv', PACKAGE = 'mpsBART4', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_mpsBART4_std_pinv', PACKAGE = 'mpsBART4', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_mpsBART4_faster_simple_std_inv', PACKAGE = 'mpsBART4', A, diag)
}

faster_std_inv <- function(A, diag) {
    .Call('_mpsBART4_faster_std_inv', PACKAGE = 'mpsBART4', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_mpsBART4_rMVN2', PACKAGE = 'mpsBART4', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_mpsBART4_rMVNslow', PACKAGE = 'mpsBART4', b, Q)
}

matrix_mat <- function(array) {
    .Call('_mpsBART4_matrix_mat', PACKAGE = 'mpsBART4', array)
}

rand_unif <- function() {
    .Call('_mpsBART4_rand_unif', PACKAGE = 'mpsBART4')
}

